version: '3.8'

services:

  database:
    image: mysql
    container_name: db_docker_symfony
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - database
    ports:
      - "8000:80"
    environment:
      PMA_HOST: database
    networks:
      - dev
  maildev:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev
  www:
    build: php
    container_name: www_docker_symfony
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

  elasticsearch:
    container_name: sb-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - "9209:9200"
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - "xpack.security.enabled=false"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
    networks:
      - dev

#     elasticsearch head manager (fork of mobz/elasticsearch-head for elasticsearch 6)
#     /!\ it isn't an official image /!\
  elasticsearch-head:
    container_name: sb-elasticsearch-head
    depends_on:
      - elasticsearch
    image: tobias74/elasticsearch-head:6
    ports:
      - "9109:9100"


networks:
  dev:

volumes:
  db-data:
